apiVersion: apps/v1
kind: Deployment
metadata:
  name: irrigation-service
  namespace: irrigation-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irrigation-service
  template:
    metadata:
      labels:
        app: irrigation-service
    spec:
      containers:
      - name: irrigation-service
        image: irrigation-service:latest
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:9999"
---
apiVersion: v1
kind: Service
metadata:
  name: irrigation-service
  namespace: irrigation-system
spec:
  selector:
    app: irrigation-service
  ports:
  - port: 8082
    targetPort: 8082
